//JavaScript code generated by API++
//API++ by Piccolowen
window.onload = apifunc();
async function apifunc() {
const url = 'https://api.github.com/repos/piccolowen/apipp';
const response = await fetch(url);
const result = await response.json();
const apiresult = document.getElementById('apippdesc-title');
console.log('api++ system working...')
console.log('api++ system by Piccolowen https://github.com/Piccolowen')
console.log('api++ result:');
const desc = document.createElement('title')
desc.className = 'class'

if (result == "undefined") {
    desc.textContent = 'API++'
}
else {
    desc.textContent = 'API++: ' + result.description
}
apiresult.appendChild(desc)
}
